name: QLCplus Windows QLC+5 Build

on:
  workflow_dispatch:

jobs:
  build-windows-v5:
    runs-on: windows-latest

    env:
      QT_VERSION: "6.10.2"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set variables
        shell: bash
        run: |
          echo "QTDIR=${{ github.workspace }}/qt/Qt/${{ env.QT_VERSION }}/mingw_64" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u '+%Y%m%d')" >> $GITHUB_ENV
          echo "GIT_REV=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "OUTFILE=$(grep 'OutFile' platforms/windows/qlcplus5Qt6.nsi | cut -d'\"' -f 2)" >> $GITHUB_ENV

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_mingw
          dir: "${{ github.workspace }}/qt/"
          modules: "qt3d qtimageformats qtmultimedia qtserialport qtwebsockets"

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          release: true
          update: false
          path-type: inherit
          install: >-
            wget
            unzip
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-gcc-libs
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-libmad
            mingw-w64-x86_64-libsndfile
            mingw-w64-x86_64-flac
            mingw-w64-x86_64-fftw
            mingw-w64-x86_64-libusb
            mingw-w64-x86_64-python-lxml
            mingw-w64-x86_64-nsis

      - name: Prepare D2XX SDK
        shell: msys2 {0}
        run: |
          mkdir -p /c/projects/D2XXSDK
          wget https://qlcplus.org/misc/CDM-v2.12.36.20-WHQL-Certified.zip -O /c/projects/D2XXSDK/cdm.zip
          cd /c/projects/D2XXSDK
          unzip cdm.zip
          cd amd64
          gendef.exe - ftd2xx64.dll > ftd2xx.def
          dlltool -k --input-def ftd2xx.def --dllname ftd2xx64.dll --output-lib libftd2xx.a

      - name: Patch Windows build files
        shell: msys2 {0}
        run: |
          sed -i -e 's/Debug/Release/g' CMakeLists.txt
          sed -i -e 's/ add_subdirectory(velleman)/# add_subdirectory(velleman)/g' plugins/CMakeLists.txt
          sed -i -e 's/$ENV{SystemDrive}\/msys64/D:\/a\/_temp\/msys64/g' platforms/windows/CMakeLists.txt
          sed -i -e 's/c\:\\projects/d:\\a\\qlcplus/g' platforms/windows/qlcplus5Qt6.nsi

      - name: Configure QLC+ 5
        shell: msys2 {0}
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH="${{ env.QTDIR }}/lib/cmake" \
            -Dqmlui=ON

      - name: Build
        shell: msys2 {0}
        run: |
          sed -i "s/\(#define APPVERSION \".*\)\"/\1 ${{ env.GIT_REV }}\"/" engine/src/qlcconfig.h
          cd build
          ninja

      - name: Install
        shell: msys2 {0}
        run: |
          cd build
          ninja install

      - name: Deploy Qt libraries
        shell: msys2 {0}
        run: |
          SRC_DIR=$PWD
          ./translate.sh release qmlui
          cp *.qm /c/qlcplus
          cd /c/qlcplus
          "${{ env.QTDIR }}/bin/windeployqt" --qmldir "$SRC_DIR/qmlui/qml" qlcplus-qml.exe qlcplusengine.dll plugins/dmxusb.dll

      - name: Build installer
        shell: msys2 {0}
        run: |
          cd /c/qlcplus
          makensis -X'SetCompressor /FINAL lzma' qlcplus5Qt6.nsi
          mv "/c/qlcplus/${{ env.OUTFILE }}" "${{ github.workspace }}/QLCplus5-${{ env.BUILD_DATE }}-${{ env.GIT_REV }}.exe"

      - name: Upload installer
        uses: actions/upload-artifact@v7
        with:
          name: QLCplus5-Windows
          path: QLCplus5-*.exe
